<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.0.42</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Suppress warning 1591 for missing XML documentation -->
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BelronUS.HttpLegacy" Version="1.0.3" />
    <PackageReference Include="System.Text.Json" Version="6.0.7" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
    <PackageReference Include="BelronUS.SDK.Base" Version="1.0.22" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <None Include="./bin/Debug/netstandard2.0/BelronUS.VehicleSDKs.V2.xml" pack="true" />
  </ItemGroup>

</Project>
